version: '3.8'

services:
  authservice:
    image: donationbox/authservice:dev
    build:
      context: .
      dockerfile: src/Services/AuthService/Dockerfile
      args:
        - BUILD_CONFIGURATION=Debug
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # DB and app settings (override as needed)
      ConnectionStrings__DefaultConnection: Server=host.docker.internal,1433;Database=AuthServiceDb_Dev;User Id=sa;Password=Pwd12345!;TrustServerCertificate=true;MultipleActiveResultSets=true
      JwtSettings__SecretKey: development-secret-jwt-key-that-is-at-least-256-bits-long-for-dev-use-only!
      JwtSettings__Issuer: AuthService-Dev
      JwtSettings__Audience: DonationBoxClients-Dev
      GoogleAuth__ClientId: 603609289505-qfs97ftap8sehj1escrshq05dg5e8dh0.apps.googleusercontent.com
      GoogleAuth__ClientSecret: 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
    volumes:
      - ./.certs:/https:ro
    restart: unless-stopped
